services:
  qdrant:
    image: qdrant/qdrant:v1.0.0
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__LOG_LEVEL: INFO
volumes:
  qdrant_data:

